/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DriverView: typeof import('./components/DriverView.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MapBox: typeof import('./components/utils/MapBox.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    RideDetails: typeof import('./components/user/RideDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideUnlock: typeof import('./components/SlideUnlock.vue')['default']
  }
}
